name: Optimize Resource Pack
on: [push]
jobs:
  packsquash:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 変更しないでください
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            allow_mods = ['OptiFine']
            maximum_width_and_height = 8192
  release:
    runs-on: ubuntu-latest
    needs: [packsquash]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download Optimized Pack
        uses: actions/download-artifact@v2
        with:
          name: Optimized pack
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pack.zip
